# Scrape data with Python to be executed in Windows' PS EXO and Azure module by sending it in a pipeline
stages:
  - build-python3
  - build-powershell

build-python3:
  tags:
   - maxim-linux
  stage: build-python3
  image: python:latest
  script:
  - pip3 install -r requirements.txt
  - python3 python-script.py
  artifacts:
    paths:
      - output.txt
    expire_in: 1 week

build-powershell:
  tags:
    - maxim-windows
  stage: build-powershell
  image: mcr.microsoft.com/windows/servercore:latest
  script:  
  - Install-PackageProvider -Name NuGet -confirm:$false -Force
  - Install-Module -Name ExchangeOnlineManagement -confirm:$false -Force
  - Import-Module ExchangeOnlineManagement 
  - Install-Module -Name AzureAD -confirm:$false -Force
  - Get-ChildItem
  - Set-Location script-location/
  - ForEach ($Line in Get-Content ../output.txt) { Invoke-Expression $Line }

  dependencies:
  - build-python3
